id = "basalt"
name = "Basalt"
version = "0.1.0"
schema_version = 1
authors = ["Basalt Contributors"]
description = "Basalt language support for Zed"
repository = "https://github.com/example/zed-basalt"

[grammars.basalt]
repository = "file:///Users/forest/Developer/basalt/zed-basalt/grammars/basalt"
rev = "ac6cba4ea1dbd32827f65a72c42c5f7353a1a783"
